### PR TITLE
Architectural changes

### PR DESCRIPTION
**Pull request by chmoder**
Hi abahgat,

I saw your skeleton code and thought there were a few things that could make it a little more out of the box friendly.  Most of these things are small but in the end are more modular and dynamic.  If for any reason you don't like the changes just reject the pull request.  But if you do, I didn't want to take your work without improving it.
## change list
- Create a base class module for the BaseHandler
- Categorize handler functionality into modules
- Combine all routes and app in one file so that `uri_for` will have scope
- Add Jinja2 and `uri_for` to jinja2 globals
- In `BaseHandler` add `template_name` and `template values` for use in `render_template`
- Set `self.template_name` and `self.template_values` before calling `self.render_template`
- Refactor all templates to use uri_for('route_name')
- Move models.py to models.user.py

### CODE REVIEW

**Comment by hiven** [comment]
Any input on this pull request? Would be interesting to see your feedback

**Comment by chmoder** [comment]
I'm not sure what to add to the message above.  Would you like to know anything in particular?

**Comment by abahgat** [comment]
Hi, thanks for your comments,
my first thought seeing this is that it'd be easier to follow if the change were organized in different commits (each addressing one point).

The main reason is that this project serves mostly a didactic purpose, so smaller, focused, changes would be easier to follow for new users.

I will take a closer look later today and get back at you.
Alessandro

**Comment by hiven** [comment]
Thank you. I'm learning to make my first Python web app on google cloud and just wondering which would be a good starting point to learn and develop. I appreciate your time.

**Comment by abahgat** [comment]
I finally had some time to look at this change again and I definitely appreciate parts of it while I am conflicted on others.
Specifically, I think breaking the application in a few smaller files would make it easier to work with (but possibly less effective as a companion to the original [walkthrough post](http://blog.abahgat.com/2013/01/07/user-authentication-with-webapp2-on-google-app-engine/).
Similarly, using jinja and its `uri_for` is a good addition for a production application, but introduces a non-webapp2 dependency on a project that was 100% focused on a specific webapp2 feature.

Overall, I'd rather avoid merging in changes that mix moves/renames/refactors (e.g. splitting handlers in multiple files) with functionality changes (e.g. introducing jinja2 support) in a single pull request, but rather have separate commits that address one point each (ideally, each entry in the "change list" section above deserves its own commit, as I see it).

My gut feeling would be that there might be value in merging the refactor changes first and consider the jinja2 change separately, but I'm curious to hear your opinion as well.

I'll also post a couple more comments regarding code formatting and specific points inline.

**Pull request closed without merging**
